In [15]:
import numpy as np
import pandas as pd

In [3]:
nums = [1,2,3,4,5]
np.mean(nums)

3.0

In [4]:
np.median(nums)

3.0

In [5]:
np.std(nums)

1.4142135623730951

In [6]:
    array = np.array([1, 4, 5, 8], float)
    print array
    print ""
    array = np.array([[1, 2, 3], [4, 5, 6]], float)  # a 2D array/Matrix
    print array


[ 1.  4.  5.  8.]

[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [7]:
    array = np.array([1, 4, 5, 8], float)
    print array
    print ""
    print array[1]
    print ""
    print array[:2]
    print ""
    array[1] = 5.0
    print array[1]

[ 1.  4.  5.  8.]

4.0

[ 1.  4.]

5.0


In [10]:
    two_D_array = np.array([[1, 2, 3], [4, 5, 6]], float)
    print two_D_array
    print ""
    print two_D_array[1][1]
    print ""
    print two_D_array[1, :]
    print ""
    print two_D_array[:, 2]

[[ 1.  2.  3.]
 [ 4.  5.  6.]]

5.0

[ 4.  5.  6.]

[ 3.  6.]


In [11]:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([5, 2, 6], float)
    print array_1 + array_2
    print ""
    print array_1 - array_2
    print ""
    print array_1 * array_2

[ 6.  4.  9.]

[-4.  0. -3.]

[  5.   4.  18.]


In [12]:
    array_1 = np.array([[1, 2], [3, 4]], float)
    array_2 = np.array([[5, 6], [7, 8]], float)
    print array_1 + array_2
    print ""
    print array_1 - array_2
    print ""
    print array_1 * array_2

[[  6.   8.]
 [ 10.  12.]]

[[-4. -4.]
 [-4. -4.]]

[[  5.  12.]
 [ 21.  32.]]


In [14]:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([[6], [7], [8]], float)
    print np.mean(array_1)
    print np.mean(array_2)
    print ""
    print np.dot(array_1, array_2)


2.0
7.0

[ 44.]


In [16]:
    series = pd.Series(['Dave', 'Cheng-Han', 'Udacity', 42, -1789710578])
    print series

0           Dave
1      Cheng-Han
2        Udacity
3             42
4    -1789710578
dtype: object


In [17]:
    series = pd.Series(['Dave', 'Cheng-Han', 359, 9001],
                       index=['Instructor', 'Curriculum Manager',
                              'Course Number', 'Power Level'])
    print series

Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
Power Level                9001
dtype: object


In [19]:
    series = pd.Series(['Dave', 'Cheng-Han', 359, 9001],
                       index=['Instructor', 'Curriculum Manager',
                              'Course Number', 'Power Level'])
    print series['Instructor']
    print ""
    print series[['Instructor', 'Curriculum Manager', 'Course Number']]


Dave

Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
dtype: object


In [20]:
    cuteness = pd.Series([1, 2, 3, 4, 5], index=['Cockroach', 'Fish', 'Mini Pig',
                                                 'Puppy', 'Kitten'])
    print cuteness > 3
    print ""
    print cuteness[cuteness > 3]

Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool

Puppy     4
Kitten    5
dtype: int64


In [21]:
    data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
    football = pd.DataFrame(data)
    print football.dtypes
    print ""
    print football.describe()
    print ""
    print football.head()
    print ""
    print football.tail()


losses     int64
team      object
wins       int64
year       int64
dtype: object

          losses       wins         year
count   8.000000   8.000000     8.000000
mean    6.625000   9.375000  2011.125000
std     3.377975   3.377975     0.834523
min     1.000000   4.000000  2010.000000
25%     5.000000   7.500000  2010.750000
50%     6.000000  10.000000  2011.000000
75%     8.500000  11.000000  2012.000000
max    12.000000  15.000000  2012.000000

   losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012

   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012
5      10    Lions     6  2010
6       6    Lions    10  2011
7      12    Lions     4  2012


In [39]:
def create_dataframe():
    '''
    Create a pandas dataframe called 'olympic_medal_counts_df' containing
    the data from the table of 2014 Sochi winter olympics medal counts.  

    The columns for this dataframe should be called 
    'country_name', 'gold', 'silver', and 'bronze'.  

    There is no need to  specify row indexes for this dataframe 
    (in this case, the rows will automatically be assigned numbered indexes).
    
    You do not need to call the function in your code when running it in the
    browser - the grader will do that automatically when you submit or test it.
    '''

    countries = ['Russian Fed.', 'Norway', 'Canada', 'United States',
                 'Netherlands', 'Germany', 'Switzerland', 'Belarus',
                 'Austria', 'France', 'Poland', 'China', 'Korea', 
                 'Sweden', 'Czech Republic', 'Slovenia', 'Japan',
                 'Finland', 'Great Britain', 'Ukraine', 'Slovakia',
                 'Italy', 'Latvia', 'Australia', 'Croatia', 'Kazakhstan']

    gold = [13, 11, 10, 9, 8, 8, 6, 5, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
    silver = [11, 5, 10, 7, 7, 6, 3, 0, 8, 4, 1, 4, 3, 7, 4, 2, 4, 3, 1, 0, 0, 2, 2, 2, 1, 0]
    bronze = [9, 10, 5, 12, 9, 5, 2, 1, 5, 7, 1, 2, 2, 6, 2, 4, 3, 1, 2, 1, 0, 6, 2, 1, 0, 1]
    
    # your code here
    data = {
        'country_name' : countries,
        'gold' : gold,
        'silver' : silver,
        'bronze' : bronze
    }
    olympic_medal_counts_df = pd.DataFrame(data);
    
    

    return olympic_medal_counts_df

In [41]:
olympic_data =  create_dataframe()
print olympic_data.head()

   bronze   country_name  gold  silver
0       9   Russian Fed.    13      11
1      10         Norway    11       5
2       5         Canada    10      10
3      12  United States     9       7
4       9    Netherlands     8       7


In [42]:
olympic_data[['country_name', 'gold']]

country_name  gold
0     Russian Fed.    13
1           Norway    11
2           Canada    10
3    United States     9
4      Netherlands     8
5          Germany     8
6      Switzerland     6
7          Belarus     5
8          Austria     4
9           France     4
10          Poland     4
11           China     3
12           Korea     3
13          Sweden     2
14  Czech Republic     2
15        Slovenia     2
16           Japan     1
17         Finland     1
18   Great Britain     1
19         Ukraine     1
20        Slovakia     1
21           Italy     0
22          Latvia     0
23       Australia     0
24         Croatia     0
25      Kazakhstan     0

In [44]:
olympic_data.loc[25]

bronze                   1
country_name    Kazakhstan
gold                     0
silver                   0
Name: 25, dtype: object

In [45]:
olympic_data[olympic_data['gold'] > 3]

bronze   country_name  gold  silver
0        9   Russian Fed.    13      11
1       10         Norway    11       5
2        5         Canada    10      10
3       12  United States     9       7
4        9    Netherlands     8       7
5        5        Germany     8       6
6        2    Switzerland     6       3
7        1        Belarus     5       0
8        5        Austria     4       8
9        7         France     4       4
10       1         Poland     4       1

In [48]:
olympic_data['country_name'][olympic_data['gold'] > 3]

0      Russian Fed.
1            Norway
2            Canada
3     United States
4       Netherlands
5           Germany
6       Switzerland
7           Belarus
8           Austria
9            France
10           Poland
Name: country_name, dtype: object

In [49]:
    data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
    football = pd.DataFrame(data)
    print football.iloc[[0]]
    print ""
    print football.loc[[0]]
    print ""
    print football[3:5]
    print ""
    print football[football.wins > 10]
    print ""
    print football[(football.wins > 10) & (football.team == "Packers")]


   losses   team  wins  year
0       5  Bears    11  2010

   losses   team  wins  year
0       5  Bears    11  2010

   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012

   losses     team  wins  year
0       5    Bears    11  2010
3       1  Packers    15  2011
4       5  Packers    11  2012

   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012


In [51]:
d = {'one' : pd.Series([1,2,3], index=['a', 'b', 'c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d'])}

In [52]:
df = pd.DataFrame(d)

In [53]:
df

one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [54]:
df.apply(np.mean)

one    2.0
two    2.5
dtype: float64

In [55]:
df['one'].map(lambda x: x>=1)

a     True
b     True
c     True
d    False
Name: one, dtype: bool

In [56]:
df.applymap(lambda x: x>= 1)

one   two
a   True  True
b   True  True
c   True  True
d  False  True

In [57]:
df = olympic_data


In [58]:
df

bronze    country_name  gold  silver
0        9    Russian Fed.    13      11
1       10          Norway    11       5
2        5          Canada    10      10
3       12   United States     9       7
4        9     Netherlands     8       7
5        5         Germany     8       6
6        2     Switzerland     6       3
7        1         Belarus     5       0
8        5         Austria     4       8
9        7          France     4       4
10       1          Poland     4       1
11       2           China     3       4
12       2           Korea     3       3
13       6          Sweden     2       7
14       2  Czech Republic     2       4
15       4        Slovenia     2       2
16       3           Japan     1       4
17       1         Finland     1       3
18       2   Great Britain     1       1
19       1         Ukraine     1       0
20       0        Slovakia     1       0
21       6           Italy     0       2
22       2          Latvia     0       2
23       1       Australia     0       2
24       0         Croatia     0       1
25       1      Kazakhstan     0       0

In [62]:
avg_bronze_at_least_one_gold = np.average(df['bronze'][df["gold"] >= 1])

In [63]:
print avg_bronze_at_least_one_gold

4.2380952381


In [65]:
pd.Series([np.average(df.gold), np.average(df.silver), np.average(df.bronze)], 
          index=['gold', 'silver', 'bronze'])

gold      3.807692
silver    3.730769
bronze    3.807692
dtype: float64

In [66]:
df[['gold','silver','bronze']].apply(np.mean)

gold      3.807692
silver    3.730769
bronze    3.807692
dtype: float64

In [67]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]

In [68]:
np.dot(a,b)

70

In [88]:
points = [4,2,1]
medal = [df.gold,
                                           df.silver,
                                           df.bronze]
totalPoints = np.dot(points, medal)

In [93]:
points_country = {
    "country_name" : df["country_name"],
    "points" : totalPoints
}

In [94]:
olympic_points_df = pd.DataFrame(points_country)

In [95]:
olympic_points_df.head()

country_name  points
0   Russian Fed.      83
1         Norway      64
2         Canada      65
3  United States      62
4    Netherlands      55